### ISSUE TITLE
Advantages?

### ISSUE THREAD

**Issue by kokujin** [philcockfield/rest-middleware#19]
This project is very nice. I have searched for hours for a project that would:
1. Work in my existing Express app.
2. Auto-generate API docs

Is there a reason why you rolled this on your own instead of using swagger, raml or apidoc?

Thanks

**Comment by philcockfield** [comment]
All those options (Swagger, RAML, APIDoc) look good.  

My creative starting point and goal for this module was to recreate the experience of working with Meteor Server Methods using pure node/express through an XHR/RESTful transport in contrast to DDP.  I then took it further to ensure that a pure and clean REST API could be modeled with a very small amount of code.

To that end, this module is a light-weight connect/express middleware (as you noticed) without a lot of fat and baggage.  But you may get more value out of the other projects you mentioned.

**Comment by airtonix** [comment]
@philcockfield well apidoc isn't a replacement for `rest-middleware`.

I'd argue that they can co-exist if we can get the doc rendering to be specifable by the project integrator.

For example (not functionally correct): 

``` es6
import ApiDocs from 'api-docs';
import RestMiddleware from 'rest-middleware';

const Rest = RestMiddleware({
  name: 'Foo',
  version: '0.0.1',
  basePath: '/api/v1'
  documentation: {
    engine: {
      render: (context, content) => ApiDocs.render(context, content)
    }
  }
});

Rest.methods({
...
})

export default Rest;
```
